name: My First Workflow
on:
  push:
    branches:
      - main
jobs:
  myFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: My First Action
        uses: actions/checkout@v5
      - name: My First Step
        run: printenv
      - name: My Second Step
        run: |
          echo "hello world" 
          echo "hi" > hello.txt
          ls 
          cat hello.txt
      - name: Sleep 
        run: sleep 20
      - name: ls repo
        run: | 
          ls
